services:
  app:
    build:
      context: .
    environment:
      DJANGO_DEBUG: "true"
      DJANGO_DB_DIR: "/var/data/app/db"
      DJANGO_ALLOWED_HOSTS: "queue-service-api.eutima.ch"
      DJANGO_TRUSTED_ORIGINS: "https://queue-service-api.eutima.ch http://localhost:4200 http://127.0.0.1:4200"
    volumes:
      - app-static-files:/var/data/app/static
      - app_db:/var/data/app/db
    restart: always

  nginx:
    image: nginx:stable-alpine3.17
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - app-static-files:/app/static:ro
      - ./nginx/gui:/app/gui:ro
    restart: always

volumes:
  app_db:
  app-static-files:
